# Site
title: 조정환
description: "Backend Engineer"
url: "https://junghwan16.github.io"
baseurl: ""

# Build
future: true
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Giscus comments
giscus:
  repo: "junghwan16/junghwan16.github.io"
  repo_id: "R_kgDOQ_xZJQ"
  category: "Announcements"
  category_id: "DIC_kwDOQ_xZJc4C2AmU"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
