# Site
title: 조정환
description: "Backend Engineer"
url: "https://junghwan16.github.io"
baseurl: ""

# Build
future: true
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
